numbers = [5, 2, 7, 5, 1, 4]
print(numbers)
numbers.append(10)
print(numbers)
numbers.insert(3, 12)
print(numbers)
numbers.remove(10)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(12))
print(12 in numbers)
print(numbers.count(5))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
numbers.append(50)
numbers.clear()
print(numbers)
print(numbers2)